version: '2'
services:
    mysql:
        container_name: mysql
        image: mysql:8.0.16
        privileged: true
        volumes:
            - /e/mysql-data:/var/lib/mysql
            - ./lnmp/mysql/conf/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app_net
    php-fpm:
        container_name: php-fpm
        image: crunchgeek/php-fpm:7.2
        privileged: true
        volumes:
            - ../logs/php-fpm/:/var/log/php-fpm/
            - /e/www:/www
            - ./lnmp/php-fpm/etc/php-fpm.d:/usr/local/etc/php-fpm.d
        depends_on:
            - mysql
        ports:
            - "9000:9000"
        networks:
            - app_net
    nginx:
        container_name: nginx
        image: nginx:1.17.1
        privileged: true
        volumes:
            - ../logs/nginx/:/var/log/nginx/
            - ./lnmp/nginx/conf.d:/etc/nginx/conf.d
            - /e/www:/www
        ports:
            - "80:80"
        links:
            - php-fpm
        networks:
            - app_net
    redis:
        container_name: redis
        image: redis:4.0.14
        privileged: true
        ports:
            - "6379:6379"
        networks:
            - app_net

networks:
    app_net:
        external: true
