version: '2'
services:
    mysql:
        container_name: mysql
        privileged: true
        build:
            context: ./mysql
            dockerfile: ./mysql-8.0.11.Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/data/mysql
            - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        networks:
            - app_net
    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: ./php-fpm-7.17.Dockerfile
        container_name: php-fpm
        privileged: true
        volumes:
            - ./php-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./php-fpm/etc/php-fpm.d/:/usr/local/etc/php-fpm.d
            - ./php-fpm/etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./log/php-fpm/:/var/log/php-fpm/
        depends_on:
            - mysql
        ports:
            - "9000:9000"
        networks:
            - app_net
    nginx:
        build:
            context: ./nginx
            dockerfile: ./nginx-1.12.2.Dockerfile
        privileged: true
        container_name: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./log/nginx/:/var/log/nginx/
            - /www/:/www/
        ports:
            - "80:80"
        links:
            - php-fpm
        networks:
            - app_net
    redis:
        ports:
            - "6379:6379"
        container_name: redis 
        privileged: true
        build:
            context: ./redis
            dockerfile: ./redis-3.2.11.Dockerfile
        networks:
            - app_net

networks:
    app_net:
        external: true
